services:
  mongodb:
    image: mongo:4.4
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"
    volumes:
      - ./db:/data/db
    networks:
      - mongo_network

  mongo-backup:
    build: .
    container_name: mongo-backup
    environment:
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
      - MONGODB_USER=admin
      - MONGODB_PASS=password
      - CRON_TIME=0 0 * * *  # Run at midnight every day
      - INIT_BACKUP=true     # Run a backup when the container starts
    volumes:
      - ./db-backup:/backup
    networks:
      - mongo_network
    depends_on:
      - mongodb

networks:
  mongo_network:
    driver: bridge 